// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// int_bnjr_discover
std::string int_bnjr_discover(int scan_time);
RcppExport SEXP _bonjour_int_bnjr_discover(SEXP scan_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type scan_time(scan_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(int_bnjr_discover(scan_time));
    return rcpp_result_gen;
END_RCPP
}
// int_bnjr_query
std::string int_bnjr_query(std::string q, int scan_time);
RcppExport SEXP _bonjour_int_bnjr_query(SEXP qSEXP, SEXP scan_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type scan_time(scan_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(int_bnjr_query(q, scan_time));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bonjour_int_bnjr_discover", (DL_FUNC) &_bonjour_int_bnjr_discover, 1},
    {"_bonjour_int_bnjr_query", (DL_FUNC) &_bonjour_int_bnjr_query, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bonjour(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
