# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_bnjr_discover <- function(scan_time = 10L) {
    .Call(`_bonjour_int_bnjr_discover`, scan_time)
}

int_bnjr_query <- function(q, scan_time = 5L) {
    .Call(`_bonjour_int_bnjr_query`, q, scan_time)
}

